### ISSUE TITLE
ShanghaiTech dataset missing download link

### ISSUE THREAD

**Issue by KyloRen1** [UCF-CRCV/TeD-SPAD#1]
Hello. Thanks for your work. 
Do you have a link to ShanghaiTech dataset? As googling it provides mainly irrelevant links or Baidu folder.
Thanks!

**Comment by KirinHao** [comment]
Hello, have you solved the problem?
I had the same problem.

**Comment by joefioresi718** [comment]
I sincerely apologize, I was not getting notifications for issues here. I used the OneDrive link here: [ShanghaiTech](https://svip-lab.github.io/dataset/campus_dataset.html)
