### ISSUE TITLE
Sorry, some files in OneDrive seems to be invalid. 

### ISSUE THREAD

**Issue by KirinHao** [UCF-CRCV/TeD-SPAD#2]
Sorry, some files in OneDrive seems to be invalid. Can you share Model Weights? Thank you very much!

**Comment by joefioresi718** [comment]
I apologize for such a late response, I did not get any notifications for this. I have uploaded the model weights to the OneDrive link, let me know if you have any trouble accessing.

**Comment by KirinHao** [comment]
Thank you for your patient reply. I have no further questions. Wish you a happy life.
---- Replied Message ----
From Joe ***@***.***> Date 02/27/2024 05:54 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [UCF-CRCV/TeD-SPAD] Sorry, some files in OneDrive seems to be invalid. (Issue #2) 
Closed #2 as completed.
