### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by LMJisshuaige** [UCF-CRCV/TeD-SPAD#6]
In your https://github.com/UCF-CRCV/TeD-SPAD/issues/new, page, I tried to run this project, but you only give the UCF-101 dataset inside, config.py you have to configure the path for UCF_Crimes dataset, XD dataset, ShanghaiTech dataset, and VISPR dataset. I didn't find them in datasets, could you please provide them with them

**Comment by joefioresi718** [comment]
Thank you for your interest in my work. I can provide you with a link to each dataset from their original sources, we used these to download each dataset. Hopefully this helps, let me know if you have any more questions.

UCF_Crime: [[link]](https://www.crcv.ucf.edu/projects/real-world/ )
ShanghaiTech: [[link]](https://svip-lab.github.io/dataset/campus_dataset.html) 
XD-Violence: [[link]](https://roc-ng.github.io/XD-Violence/)
VISPR: [[link]](https://tribhuvanesh.github.io/vpa/)
